name: Publish

on: [push, pull_request]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - run: |
          touch .env
          echo awsAccessKeyId=${{ secrets.AWSACCESSKEYID }} >> .env
          echo awsSecretKey=${{ secrets.AWSSECRETKEY }} >> .env
          echo region=${{ secrets.REGION }} >> .env
          echo tableName=${{ secrets.TABLENAME }} >> .env
          echo pk=${{ secrets.PK }} >> .env
          echo sk=${{ secrets.SK }} >> .env
          deno test --allow-read --allow-env --allow-net
          rm .env
      - run: |
          deno install -A -f --unstable --no-check https://x.nest.land/eggs@0.3.8/eggs.ts
          eggs link ${{ secrets.NESTAPIKEY }}
          eggs publish --yes
